#!/usr/bin/env python3
"""Dev-only: regenerate the faithfulness oracle by running the CURRENT
merge_lek_docx.py (v5) on the bundled template + sample datasource.

The ../docx/..._OUTPUT.docx fixture is STALE (generated by an older script
version) and must NOT be used as the diff target. Run this first, then:

    python3 scripts/lek-gen-oracle.py
    ./node_modules/.bin/tsx scripts/lek-verify.ts

Requires python-docx (available in the parent asguard/nadine Python project).
"""
import importlib.util
import os
from docx import Document

HERE = os.path.dirname(os.path.abspath(__file__))
DOCX_DIR = os.path.normpath(os.path.join(HERE, "..", "..", "docx"))
TEMPLATE = os.path.join(DOCX_DIR, "LEK - 1 DRAAFT.docx")
DATASOURCE = os.path.join(DOCX_DIR, "Laporan Evaluasi Kinerja_LEK-2_PEK26030906590731841 (1).docx")
OUT = "/tmp/lek_v5_output.docx"

spec = importlib.util.spec_from_file_location("merge_lek_docx", os.path.join(DOCX_DIR, "merge_lek_docx.py"))
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)

tmpl = Document(TEMPLATE)
ds = Document(DATASOURCE)
matches = m.match_sections_by_para(
    m.build_sections(tmpl, m.get_document_flow(tmpl)),
    m.build_sections(ds, m.get_document_flow(ds)),
)
filled = 0
for (_t_para, t_tables), ds_match in matches:
    if ds_match is None:
        continue
    ds_logical = m.merge_section_tables(ds, ds_match[1])
    if not ds_logical:
        continue
    filled += m.distribute_data_to_tables(tmpl, t_tables, ds_logical)
updated = m.update_dynamic_paragraphs(tmpl, ds)
tmpl.save(OUT)
print(f"saved {OUT} | filled={filled} | paras={updated}")
