name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip dist
        run: cd dist && zip -r ../asguard-ext.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: asguard-ext.zip
          generate_release_notes: true
